"""
===============================================
01. Extract events from the stimulus channels

this code is used to check and plot the timings
of triggers and creates -eve.fif file and generates
an HTML report file

written by Tara Ghafari
adapted from Oscar Ferrante 
==============================================  
ToDos:
    1) Run the code for other tasks (emoface
                                     CRT
                                     rest
                                     noise)
Issues:
    1) generate the report when mne.Report reads
    bids event file
Contributions to Community:
    1) 
Questions:
    1) 
"""

# Import relevant Python modules
import os.path as op
import os

import mne
import matplotlib.pyplot as plt

# fill these out- only change the first three for Nottingham
site = 'Nottingham'
subj_code = '13586013'  # subject code generated by participant/MEG pc
subject = '01'  # subject code in mTBI project
session = '01'  # data collection session within each run
run = '01'  # data collection run for each participant
pilot = 'NP' # is the data collected 'P'ilot or 'T'ask or NP (Nottingham Pilot)?
day = '15'  # date of data collection -> removed after anonymization
month = '03'
year = '2023'

data_root = r'Z:\Projects\mTBI_predict\Collected_Data'
MEG_data_folder = op.join(data_root, 'MEG_data\Raw-Pilot_Participants')  # RDS folder for MEG data

report = True  # do you want to generate a report?
    
# MEG bids conversion
""" using the events extracted from the MEG file, we now convert MEG file to
bids format"""

tasks = ['SpAtt', 'CRT', 'EmoFace','rest']   # short name of task
for task in tasks:
    
    if site == 'Aston' or site == 'Birmingham':
        data_path = op.join(MEG_data_folder, year + month + day + '_' + subj_code, 
                            year[-2:] + month + day)
        file_extension = '.fif'
        file_name = op.join('sub_' + pilot + '1' + subject + '_ses_' + session +
                            '_task_' + task + '_run_' + run + '_meg')
    elif site == 'Nottingham':
        data_path = op.join(MEG_data_folder, 'Nottingham_' + pilot + subject, pilot + subject)
        file_prename = subj_code + '_mTBIPredict_'
        file_extension = '.ds'
        file_name = op.join(file_prename + year + month + day + '_' + task)
    
    # Report folder names
    if report:
        report_root = r'Z:\Projects\mTBI_predict\Results-Outputs\mne-Reports'  # RDS folder for reports
        if not op.exists(op.join(report_root , 'sub-' + subject, 'task-' + task)):
            os.makedirs(op.join(report_root , 'sub-' + subject, 'task-' + task))
        report_folder = op.join(report_root , 'sub-' + subject, 'task-' + task)
        report_fname = op.join(report_folder, 'report_events.html')
    
    # specify communal file names
    raw_fname = op.join(data_path, file_name + file_extension)
    filename_events = op.join(data_path, file_name + '-eve' + file_extension)
    
    # read raw and define the stim channel
    if 'fif' in file_extension:
        raw = mne.io.read_raw_fif(raw_fname, allow_maxshield=True, 
                                  verbose=True, preload=False)
        stim_channel = 'STI101'
    
    elif 'ds' in file_extension:
        raw = mne.io.read_raw_ctf(raw_fname, system_clock='truncate', 
                                  verbose=True, preload=True)
        stim_channel = 'UPPT002'
        
    # Read the events from stim channel
    events = mne.find_events(raw, stim_channel=stim_channel, min_duration=0.001001,
                             consecutive=False, mask=65280,
                             mask_type='not_and')  #' mask removes triggers associated
                                                   # with response box channel 
                                                   # (not the response triggers)'

    # Save the events in a dedicted FIF-file: 
    mne.write_events(filename_events, events, overwrite=True)
        
    # Report the events file
    sfreq = raw.info['sfreq']
    if report == True:
        report = mne.Report(title='Events')
        report.add_events(events=events, title='events from "events"', sfreq=sfreq)
        report.save(report_fname, overwrite=True, open_browser=True)
    
    # Plot the raw stim channel - this line only for fif so far
    raw.pick_types(meg=False, stim=True).plot()
    
    # Visualise a part of the events-array
    plt.figure()
    plt.stem(events[:,0], events[:,2])
    plt.xlim(min(events[:,0]), min(events[:,0])+100000)
    plt.title(task)
    plt.xlabel('sample')
    plt.ylabel('Trigger value (STI101)')

plt.show()  # show all plots together





